services:

  backend:
    container_name: backend

    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        USER: ${USER}

    volumes:
      - ./backend:/var/www/html

    depends_on:
      - db
      - redis
    networks:
      - minha_sala_anhanguera

    command: |
      bash -c "[ ! -d 'vendor' ] && composer install && php artisan serve --host=0.0.0.0 --port=8000 || php artisan serve --host=0.0.0.0 --port=8000"

    ports:
      - "127.0.0.1:8000:8000"

  frontend:
    container_name: frontend

    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}

    volumes:
      - ./frontend:/app

    command: |
      bash -c "[ ! -d 'node_modules' ] && yarn install && yarn dev --host 0.0.0.0 --port 5173 || yarn dev --host 0.0.0.0 --port 5173"

    networks:
      - minha_sala_anhanguera

    ports:
      - "127.0.0.1:5173:5173"

  db:
    container_name: db
    image: mysql:8.0.30
    restart: unless-stopped

    volumes:
      - db_data:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

    networks:
      - minha_sala_anhanguera

    ports:
      - "127.0.0.1:3306:3306"

  redis:
    image: redis:7.4.1
    container_name: redis_server
    ports:
      - "127.0.0.1:6379:6379" 
    volumes:
      - redis_data:/data 
    restart: always 
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - minha_sala_anhanguera
    command: ["sh", "-c", "redis-server --requirepass $REDIS_PASSWORD"]

networks:
  minha_sala_anhanguera:
    driver: bridge

volumes:
  db_data:
  redis_data:
